=== ZaherZohbi/ull-etsii-geobloc/GeoBloc_desktop/src/dtd/GeoBlocFormsDTDv1.3.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Elements struct -->
<!ELEMENT gb_form (gb_name, gb_version, gb_date, gb_formDescription, (gb_dataPage|gb_photoPage|gb_videoPage|gb_audioPage|gb_locationPage)+)>
    <!ELEMENT gb_name (#PCDATA)>
    <!ELEMENT gb_version (#PCDATA)>
    <!ELEMENT gb_date (gb_dateDay, gb_dateMonth, gb_dateYear)>
        <!ELEMENT gb_dateDay (#PCDATA)>
        <!ELEMENT gb_dateMonth (#PCDATA)>
        <!ELEMENT gb_dateYear (#PCDATA)>
    <!ELEMENT gb_formDescription (#PCDATA)>

    <!ELEMENT gb_dataPage (gb_pageName,(gb_label|gb_field|gb_list|gb_checkbox|gb_checkboxthree)+)>
        <!ELEMENT gb_pageName (#PCDATA)>
        <!ELEMENT gb_label (gb_description?, gb_labelText)>
            <!ELEMENT gb_description (#PCDATA)>
            <!ELEMENT gb_labelText (#PCDATA)>
        <!ELEMENT gb_field (gb_description?, gb_fieldLabel, gb_fieldDefaultValue?)>
            <!-- <gb_description> -->
            <!ELEMENT gb_fieldLabel (#PCDATA)>
            <!ELEMENT gb_fieldDefaultValue (#PCDATA)>
        <!ELEMENT gb_checkbox (gb_description?, gb_checkboxText, gb_checkboxDefaultValue?)>
            <!-- <gb_description> -->
            <!ELEMENT gb_checkboxText (#PCDATA)>
            <!ELEMENT gb_checkboxDefaultValue (#PCDATA)>
            <!-- 0, 1 or 2-->
        <!ELEMENT gb_list (gb_description?, gb_listLabel, gb_listItem+)>
            <!-- <gb_description> -->
            <!ELEMENT gb_listLabel (#PCDATA)>
            <!ELEMENT gb_listItem (gb_listItemLabel, gb_listItemValue)>
                <!ELEMENT gb_listItemLabel (#PCDATA)>
                <!ELEMENT gb_listItemValue (#PCDATA)>


	<!ELEMENT gb_photoPage (gb_pageName, gb_description)>

	<!ELEMENT gb_videoPage (gb_pageName, gb_description)>

	<!ELEMENT gb_audioPage (gb_pageName, gb_description)>

	<!ELEMENT gb_locationPage (gb_pageName, gb_description)>


<!-- Attributes -->
<!ATTLIST gb_dataPage
    id CDATA #REQUIRED
>

<!ATTLIST gb_photoPage
    id CDATA #REQUIRED
    isRequired (true|false) "false"
>

<!ATTLIST gb_videoPage
    id CDATA #REQUIRED
    isRequired (true|false) "false"
>

<!ATTLIST gb_audioPage
    id CDATA #REQUIRED
    isRequired (true|false) "false"
>

<!ATTLIST gb_locationPage
    id CDATA #REQUIRED
    isRequired (true|false) "false"
>

<!ATTLIST gb_label
    id CDATA #REQUIRED
>

<!ATTLIST gb_field
    id CDATA #REQUIRED
    isRequired (true|false) "false"
    type (string|integer|float) #REQUIRED
    linesNumber CDATA "1"
>

<!ATTLIST gb_list
    id CDATA #REQUIRED
    isRequired (true|false) "false"
    type (single|multiple|combo) #REQUIRED
>

<!ATTLIST gb_listItem
    selected (true|false) "false"
>

<!ATTLIST gb_checkbox
    id CDATA #REQUIRED
    isRequired (true|false) "false"
>

<!ATTLIST gb_label
    id CDATA #REQUIRED
>

=== ZaherZohbi/ull-etsii-geobloc/GeoBloc_desktop/src/dtd/test2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gb_form SYSTEM "http://ull-etsii-geobloc.googlecode.com/files/GeoBlocFormsDTDv1.3.dtd">

<gb_form>
  <gb_name>test1</gb_name>
  <gb_version>1.0</gb_version>
  <gb_date>
    <gb_dateDay>5</gb_dateDay>
    <gb_dateMonth>7</gb_dateMonth>
    <gb_dateYear>2010</gb_dateYear>
  </gb_date>
  <gb_formDescription>Formulario básico de prueba</gb_formDescription>
  <gb_dataPage id="page01">
    <gb_pageName>page1</gb_pageName>
    <gb_label id="label01">
      <gb_labelText>Etiqueta de prueba en pagina 1</gb_labelText>
    </gb_label>
    <gb_field id="field01" type="string" linesNumber="1" isRequired="false">
      <gb_description>Descripción del campo de prueba</gb_description>
      <gb_fieldLabel>Campo de texto de prueba</gb_fieldLabel>
      <gb_fieldDefaultValue>Valor por defecto</gb_fieldDefaultValue>
    </gb_field>
    <gb_list id="single01" type="single" isRequired="false">
      <gb_description>Descripción de la single list</gb_description>
      <gb_listLabel>Single list de prueba</gb_listLabel>
      <gb_listItem selected="false">
        <gb_listItemLabel>Opción A</gb_listItemLabel>
        <gb_listItemValue>Valor 1</gb_listItemValue>
      </gb_listItem>
      <gb_listItem selected="false">
        <gb_listItemLabel>Opción B</gb_listItemLabel>
        <gb_listItemValue>Valor 2</gb_listItemValue>
      </gb_listItem>
    </gb_list>
  </gb_dataPage>
  <gb_dataPage id="page02">
    <gb_pageName>page2</gb_pageName>
    <gb_label id="label02">
      <gb_labelText>Etiqueta de prueba en pagina 2</gb_labelText>
    </gb_label>
    <gb_list id="multiple01" type="multiple" isRequired="true">
      <gb_listLabel>Multiple list de prueba</gb_listLabel>
      <gb_listItem selected="true">
        <gb_listItemLabel>Opción A</gb_listItemLabel>
        <gb_listItemValue>Valor 1</gb_listItemValue>
      </gb_listItem>
      <gb_listItem selected="false">
        <gb_listItemLabel>Opción B</gb_listItemLabel>
        <gb_listItemValue>Valor 2</gb_listItemValue>
      </gb_listItem>
    </gb_list>
  </gb_dataPage>
</gb_form>

=== ZaherZohbi/ull-etsii-geobloc/GeoBloc_desktop/src/dtd/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gb_form SYSTEM 'D:\Clases\Proyecto\GeoBloc_desktop\src\dtd\GeoBlocFormsDTDv1.3.dtd'>
<gb_form>
  <gb_name>Element drawing test</gb_name>
  <gb_version>2.0</gb_version>
  <gb_date>
    <gb_dateDay>10</gb_dateDay>
    <gb_dateMonth>2</gb_dateMonth>
    <gb_dateYear>2010</gb_dateYear>
  </gb_date>
  <gb_formDescription>Drawing test for all kind of elements</gb_formDescription>
  <gb_dataPage id="page01">
    <gb_pageName>PAGE 1</gb_pageName>
    <gb_label id="label01">
      <gb_labelText>Label1</gb_labelText>
    </gb_label>
    <gb_field id="field01" type="string" linesNumber="1" isRequired="false">
      <gb_fieldLabel>Field 1</gb_fieldLabel>
    </gb_field>
    <gb_field id="field02" type="integer" linesNumber="2" isRequired="true">
      <gb_fieldLabel>Field 2</gb_fieldLabel>
      <gb_fieldDefaultValue>500</gb_fieldDefaultValue>
    </gb_field>
    <gb_list id="list01" type="single" isRequired="false">
      <gb_listLabel>Single List 1</gb_listLabel>
      <gb_listItem>
        <gb_listItemLabel>Radio 1</gb_listItemLabel>
        <gb_listItemValue>R1</gb_listItemValue>
      </gb_listItem>
      <gb_listItem>
        <gb_listItemLabel>Radio 2</gb_listItemLabel>
        <gb_listItemValue>R2</gb_listItemValue>
      </gb_listItem>
    </gb_list>
    <gb_list id="list02" type="multiple" isRequired="false">
      <gb_listLabel>Multiple List 1</gb_listLabel>
      <gb_listItem>
        <gb_listItemLabel>Checkbox 1</gb_listItemLabel>
        <gb_listItemValue>CB1</gb_listItemValue>
      </gb_listItem>
      <gb_listItem>
        <gb_listItemLabel>Checkbox 2</gb_listItemLabel>
        <gb_listItemValue>CB2</gb_listItemValue>
      </gb_listItem>
    </gb_list>
    <gb_list id="list03" type="combo" isRequired="false">
      <gb_listLabel>Combo Box 1</gb_listLabel>
      <gb_listItem>
        <gb_listItemLabel>Combo 1</gb_listItemLabel>
        <gb_listItemValue>C1</gb_listItemValue>
      </gb_listItem>
      <gb_listItem>
        <gb_listItemLabel>Combo 2</gb_listItemLabel>
        <gb_listItemValue>C2</gb_listItemValue>
      </gb_listItem>
      <gb_listItem>
        <gb_listItemLabel>Combo 3</gb_listItemLabel>
        <gb_listItemValue>C3</gb_listItemValue>
      </gb_listItem>
    </gb_list>
  </gb_dataPage>
</gb_form>

=== ZaherZohbi/ull-etsii-geobloc/trunk/GeoBloc_desktop/src/dtd/test0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gb_form SYSTEM "http://ull-etsii-geobloc.googlecode.com/files/GeoBlocFormsDTDv1.3.dtd">

<gb_form>
  <gb_name>test0</gb_name>
  <gb_version>10</gb_version>
  <gb_date>
    <gb_dateDay>5</gb_dateDay>
    <gb_dateMonth>7</gb_dateMonth>
    <gb_dateYear>2010</gb_dateYear>
  </gb_date>
  <gb_formDescription>LONG LONG LONG LONG LONG LONG LONG LONG LONG LONG LONG LONG LONG LONG LONG LONG LONG LONG LONG LONG LONG LONG LONG LONG LONG LONG LONG LONG LONG LONG LONG</gb_formDescription>
  <gb_dataPage id="page01">
    <gb_pageName>page1</gb_pageName>
    <gb_label id="label01">
      <gb_labelText>Etiqueta de prueba</gb_labelText>
    </gb_label>
  </gb_dataPage>
</gb_form>
